package systemLogic;

public enum LogType {
	USER_LOGINNED,
	USER_LOGOUT,
	PASSWORD_CHANGED,
	USER_ADDED,
	USER_DELETED,
	MESSAGE_SENT,
	COURSE_CREATED,
	COURSE_DELETED,
	NEW_ORDER_TO_SUPPORT,
	ORDER_ACCEPTED,
	ORDER_DONE
}
